_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 2
                - 14
                - 17
                - 23
                - 24
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activationFunction:
    value: Mish
batchNormalisation:
    value: "yes"
dataAugmentation:
    value: "no"
dropout:
    value: 0.2
filterOrganisation:
    value: same
filters:
    value: 64
